version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mybotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    command: python bot/main.py
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - bot/.env
    depends_on:
      - db

volumes:
  postgres_data:
