services:
  bot:
    build: .
    container_name: telegram_bot
    env_file:
      - ./bot/.env
    depends_on:
      - db
    networks:
      - botnet

  db:
    image: 'postgres:latest'
    container_name: ai_telegram_bot-db-1
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mybotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - botnet

networks:
  botnet:
    driver: bridge

volumes:
  postgres_data:
